---
# 1. Applicable only for machines with the same password
# 2. Only sets the authorized key for the root user
- name: Set authorized key for user root
  authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
