---
- name: Checking listen port for haproxy service
  debug:
    msg: >-
      When enabling haproxy + keepalived, kube_vip_port cannot be set to 6443. You can edit globals.yml to modify it. It is recommended to use listen port 8443.
  failed_when: true
  connection: local
  run_once: True
  when:
    - kube_vip_port == 6443
    - enable_haproxy | bool
